# Generated by Django 4.2.4 on 2024-12-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WinterArc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('phone', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_photo', models.ImageField(upload_to='profile_photos/')),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
