# Generated by Django 4.2.4 on 2025-01-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WinterArc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstats',
            name='average',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='economy',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
