# Generated by Django 4.2.4 on 2024-12-21 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WinterArc', '0002_pendingregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingregistration',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='playerregistration',
            name='approved',
        ),
    ]
