# Generated by Django 4.2.4 on 2024-12-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WinterArc', '0003_remove_pendingregistration_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerregistration',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
