# Generated by Django 4.2.4 on 2025-01-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WinterArc', '0003_alter_playerstats_average_alter_playerstats_economy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorecard',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='pendingregistration',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='average',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='economy',
            field=models.FloatField(default=0.0),
        ),
    ]
