# Generated by Django 4.2.4 on 2025-01-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WinterArc', '0004_remove_scorecard_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingregistration',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='average',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='economy',
            field=models.FloatField(null=True),
        ),
    ]
