# Generated by Django 4.2.4 on 2024-12-21 17:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WinterArc', '0004_pendingregistration_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerregistration',
            name='id',
            field=models.BigAutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
